-- 005_update_proyectos.sql
-- Add calculation fields to proyectos table

ALTER TABLE public.proyectos
ADD COLUMN IF NOT EXISTS tipo_construccion TEXT,
ADD COLUMN IF NOT EXISTS largo DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS ancho DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS alto DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS area DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS porcentaje_desperdicio DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS sugerencia TEXT,
ADD COLUMN IF NOT EXISTS ai_image_path TEXT,
ADD COLUMN IF NOT EXISTS ai_image_source TEXT;
